---
title: "Build Model"
output: html_notebook
---

```{r}
library(data.table)
library(sp)
library(xgboost)
library(parallel)
library(zoo)

options(scipen=99999)
source("lib.R")
```

```{r cluster_grids}
load("../DERIVED/DATA/NIJ2012-2015_grid#_added.Rdata")
load("../DERIVED/grids_SpatialPolygons.Rdata")

panel <- subset(panel, grid!=0)
panel[,occ_date:=as.Date(occ_date)]
setorder(panel,"occ_date","grid")
areas <- unlist(lapply(panel$grid,function(x) return(s_polygons@polygons[[x]]@area)))
panel[,grid_area:=areas]

# Create a panel of all grids
grids <- data.table(grid=1:length(s_polygons@polygons), x = coordinates(s_polygons)[,1], 
                    y = coordinates(s_polygons)[,2])
areas =(unlist(lapply(1:67372,function(x) return(s_polygons@polygons[[x]]@area))))
grids[,grid_area:=areas]

# Transform coordinates into latitude longitude
pts <- SpatialPointsDataFrame(coords = grids[,2:3,with=F],data=grids[,1,with=F])
proj4string(pts) <- CRS("+init=epsg:2913")
pts <- spTransform(pts, CRS("+init=epsg:4326"))
grids$x <- coordinates(pts)[,1]; grids$y <- coordinates(pts)[,2]

# Cluster grids on the basis of latitude longitude
grids[,dist_xy := sqrt(x^2+y^2)]
setorder(grids,"dist_xy")
grids[,grid_cluster:=sort(rep(1:135,500))]
setnames(grids,"x","centroid_long")
setnames(grids,"y","centroid_lat")
save(grids, file = "../DERIVED/grids_info.Rdata")

```

```{r aggregate_grid_date_crimeType}
load("../DERIVED/grids_info.Rdata")
# Aggregate panel to grid-date-crime-type level
panel_grid_crime <- panel[,list(num_crimes=.N),by=c("grid","occ_date","CATEGORY","grid_area")]
rm(panel)
gc()

# Create a complete mapping of dates starting Aug'15 till May'15 with all grids 
dates <- data.table(occ_date = seq.Date(as.Date("2014-01-01"),as.Date("2015-12-31"),by = "1 day"), count=1)
grids[,count:=1]

panel_master <- merge(grids[,c(1:4,6:7),with=F],dates,by="count",allow.cartesian=T)
panel_master[,count:=NULL]
```

```{r build_model_StreetCrime_(i)Data Prep}
panel_SC <- merge(panel_master, panel_grid_crime[CATEGORY=="STREET CRIMES",c(1,2,5),with=F], by=c("grid","occ_date"), all.x=T)
panel_SC[is.na(num_crimes),num_crimes:=0]

# get the 1 week, 2 week, 1 month, 2 month, 3 month target variable
setorder(panel_SC,"grid","occ_date")
panel_SC[,target_7:=c(rollsum(num_crimes,k=7),rep(NA,6)),by="grid"]
panel_SC[,target_14:=c(rollsum(num_crimes,k=14),rep(NA,13)),by="grid"]
panel_SC[,target_28:=c(rollsum(num_crimes,k=28),rep(NA,27)),by="grid"]
panel_SC[,target_56:=c(rollsum(num_crimes,k=56),rep(NA,55)),by="grid"]
panel_SC[,target_84:=c(rollsum(num_crimes,k=84),rep(NA,83)),by="grid"]

# get last day, 2 days, 3 days, 1 week, 2 week, 1 month, 2 month historical variables
setorder(panel_SC,"grid",-"occ_date")
panel_SC[,last_1:=c(rollsum(num_crimes,k=2),rep(NA,1))-num_crimes,by="grid"]
panel_SC[,last_2:=c(rollsum(num_crimes,k=3),rep(NA,2))-num_crimes,by="grid"]
panel_SC[,last_3:=c(rollsum(num_crimes,k=4),rep(NA,3))-num_crimes,by="grid"]
panel_SC[,last_7:=c(rollsum(num_crimes,k=8),rep(NA,7))-num_crimes,by="grid"]
panel_SC[,last_14:=c(rollsum(num_crimes,k=15),rep(NA,14))-num_crimes,by="grid"]
panel_SC[,last_28:=c(rollsum(num_crimes,k=29),rep(NA,28))-num_crimes,by="grid"]
panel_SC[,last_56:=c(rollsum(num_crimes,k=57),rep(NA,56))-num_crimes,by="grid"]
panel_SC[,last_84:=c(rollsum(num_crimes,k=85),rep(NA,84))-num_crimes,by="grid"]

save(panel_SC,file = "../DERIVED/PANELS/panel_master_streetcrime_14_15.Rdata")

# Get the neighbourhood level detals for all grids that have had at least one crime
rm(list=ls()[!ls() %in% c("panel_SC","grids","getNeighbourHoodHistory")])
gc()

Sys.time()
cl <- makeCluster(getOption("cl.cores", 3))
clusterExport(cl, c("panel_SC","grids","getNeighbourHoodHistory"))
p <- parLapply(cl = cl, X=grids$grid,fun = function(x){
  library(data.table)
  library(geosphere)
  neighbourhood_hist_grid <- getNeighbourHoodHistory(panel_SC,grids_coord = grids[,1:3,with=F], 
                                                     radius=1, vars=colnames(panel_SC)[13:20], 
                                                     agg.by = "occ_date", gridnum=x)
  if(nrow(neighbourhood_hist_grid)==0)
    return(NULL)
  else{
    return(neighbourhood_hist_grid)
  }
})
Sys.time()
stopCluster(cl=cl)
rm(panel_SC)
gc()
neighbourhood_hist_allgrids <- rbindlist(p)
rm(p); rm(cl)
gc()

save(neighbourhood_hist_allgrids,file="../DERIVED/NEIGHBOURHOOD/neighbourhood1km_hist_all_grids_14_15.Rdata")
rm(neighbourhood_hist_allgrids)
gc()
```

```{r build_model_StreetCrime_(i)train_model}
training_grids <- read.csv(file = "../DERIVED/final_grids_SC.csv")

# Get the training and test data; # Both training & test to contain grids based on geography
load("../DERIVED/PANELS/panel_master_streetcrime_14_15.Rdata")
train_SC <- subset(panel_SC, occ_date>=as.Date("2014-01-01") & occ_date<=as.Date("2015-02-15") & grid %in% training_grids$grid)
test_SC <- subset(panel_SC, occ_date==as.Date("2015-03-01"))
rm(panel_SC)
gc()

# Merge the Neighbourhood details
load("../DERIVED/NEIGHBOURHOOD/neighbourhood1km_hist_all_grids.Rdata")
neighbourhood_hist_allgrids[is.na(neighbourhood_hist_allgrids)] = 0
train_SC <- merge(train_SC, neighbourhood_hist_allgrids,by=c("grid","occ_date"),all.x=T)
test_SC <- merge(test_SC, neighbourhood_hist_allgrids,by=c("grid","occ_date"),all.x=T)
rm(neighbourhood_hist_allgrids)
gc()

# add dow and month
train_SC[,dow:= as.factor(strftime(occ_date,"%u"))]
train_SC[,month:= as.factor(strftime(occ_date,"%m"))]
test_SC[,dow:= as.factor(strftime(occ_date,"%u"))]
test_SC[,month:= as.factor(strftime(occ_date,"%m"))]

# Define target variable by select top 100 grids for target_7 for each date
cols.select = c("dow","month","last_1","last_2","last_3","last_14","last_28","last_56",
                       "neighbourhood_last_14", "neighbourhood_last_28", "neighbourhood_last_56")
x_train <- train_SC[,cols.select,with=F]
y_train <- train_SC[,target_28]

x_test <- test_SC[,cols.select,with=F]
y_test <- test_SC[,target_28]

cols.fac <- names(which(sapply(x_train,class)=="factor"))
if(length(cols.fac)>0){
  x_train <- x_train[,(cols.fac):=lapply(.SD,function(x) as.numeric(x)), .SDcols=cols.fac]
  x_test <- x_test[,(cols.fac):=lapply(.SD,function(x) as.numeric(x)), .SDcols=cols.fac]
}

x_train[is.na(x_train)] = -999
x_test[is.na(x_test)] = -999

set.seed(123)
indx <- sample(1:nrow(x_train),nrow(x_train),replace = F)
x_train <- x_train[indx,]
y_train <- y_train[indx]

param <- list(max_depth = 5, 
              eta = 0.01, 
              silent = 1,
              objective="reg:linear",
              subsample = 0.75,
              min_child_weight = 15,
              colsample_bytree = 0.75)

train.xg <- xgb.DMatrix(data = as.matrix((x_train)), label=y_train, missing=-999)
test.xg <- xgb.DMatrix(as.matrix((x_test)), missing=-999)
gc()

Sys.time()
set.seed(123)
model_xgb <- xgb.train(data=train.xg, nrounds = 300,
                       params = param, verbose = 1, missing = -999, 
                       #early.stop.round = 200, 
                       maximize = F, print.every.n = 100
                       #watchlist = watchlist
                       )
Sys.time()

Sys.time()
pred_test = predict(model_xgb, test.xg, ntreelimit=model_xgb$bestInd, missing=-999)
Sys.time()
test_SC[,pred_target_28:=pred_test]
```

```{r build_model_StreetCrime_(i)predict_hotspots}
# Predicting for top 200 cells
setorder(test_SC,-"target_28")
actual_spots <- test_SC[1:100,grid]
setorder(test_SC,-"pred_target_28")
pred_spots <- test_SC[1:100,grid]
length(intersect(actual_spots,pred_spots))
imp <- xgb.importance(feature_names = cols.select, model = model_xgb)
```

```{r build_model_StreetCrime_(i)eval_performance}
totalarea <- sum(grids$grid_area)
effectiveness <- (sum(test_SC[grid %in% pred_spots,target_7]) / sum(test_SC[,target_7])) / (sum(test_SC[grid %in% pred_spots,grid_area]) / totalarea)
print(effectiveness)
efficiency <- sum(test_SC[grid %in% pred_spots,target_7])/sum(test_SC[grid %in% actual_spots,target_7])
print(efficiency)
# effectiveness = 66.40609 efficiency = 0.3459119
```



